query OrgUnits($fromDate: DateTime) {
  org_units(parents: null, from_date: $fromDate) {
    objects {
      addresses {
        name
        address_type {
          name
          scope
        }
      }
      name
      uuid
      children {
        name
        uuid
      }
    }
  }
}
