// Codegen plugin: the names of the DateTime fields Naldo's queries select. The
// GraphQL client converts every response field with one of these names, so
// generation fails if a query would make a name mean something else:
// - a DateTime field selected under an alias
// - another field, or an alias, using one of the names
// Insights builds its queries as strings at runtime, so they aren't checked here.
const { TypeInfo, getNamedType, visit, visitWithTypeInfo } = require("graphql")

// Every field selection in the documents, with its schema type.
const selections = (schema, documents) => {
  const found = []
  const typeInfo = new TypeInfo(schema)
  for (const { document, location } of documents) {
    visit(
      document,
      visitWithTypeInfo(typeInfo, {
        Field(node) {
          const type = typeInfo.getType()
          if (!type) return
          found.push({
            location,
            name: node.name.value,
            key: node.alias?.value ?? node.name.value,
            isDateTime: getNamedType(type).name === "DateTime",
          })
        },
      })
    )
  }
  return found
}

module.exports = {
  plugin: (schema, documents) => {
    const found = selections(schema, documents)
    const names = new Set(found.filter((s) => s.isDateTime).map((s) => s.name))

    const problems = found
      .filter((s) => (s.isDateTime ? s.key !== s.name : names.has(s.key)))
      .map((s) =>
        s.isDateTime
          ? `${s.location}: DateTime field "${s.name}" is aliased as "${s.key}"`
          : `${s.location}: "${s.key}" is not a DateTime field here`
      )
    if (problems.length) {
      throw new Error(`DateTime field names are ambiguous:\n${problems.join("\n")}`)
    }

    return [
      "// Generated by codegen/dateTimeFields.cjs from MO's schema and Naldo's queries.",
      // Formatted the way the pre-commit Prettier hook writes it.
      `export const dateTimeFields = [${[...names]
        .sort()
        .map((name) => JSON.stringify(name))
        .join(", ")}]`,
      "",
    ].join("\n")
  },
}
